In [1]:
!pip install faker

Requirement already satisfied: faker in d:\softwares\anaconda3\lib\site-packages (40.19.1)
Requirement already satisfied: tzdata in d:\softwares\anaconda3\lib\site-packages (from faker) (2025.2)

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

faker = Faker()

In [3]:
n_users= 10000

In [4]:
users = []
for i in range(1, n_users + 1):
    users.append({
        "user_id": i,
        "user_name": faker.user_name(),
        "register_date":faker.date_between(
            start_date="-2y",
            end_date="today")
    })
users_df = pd.DataFrame(users)
users_df.head()

   user_id     user_name register_date
0        1       yporter    2024-09-14
1        2        john17    2025-11-22
2        3  denisewright    2025-03-28
3        4  delacruzryan    2026-05-15
4        5    laurayoung    2025-03-05

In [5]:
users_df.to_csv("raw_users.csv",index=False)

In [6]:
n_photos = 50000
photos=[]
for i in range(1,n_photos + 1):
    photos.append({
        "photo_id": i,
        "user_id": random.randint(1,n_users),
        "upload_time": faker.date_time_this_year()
    })
photos_df = pd.DataFrame(photos)
photos_df.head()

   photo_id  user_id         upload_time
0         1     4737 2026-04-11 01:22:37
1         2     4549 2026-04-09 16:59:38
2         3     7583 2026-04-05 06:39:31
3         4     6762 2026-04-21 03:55:04
4         5     7429 2026-03-06 09:40:48

In [7]:
photos_df.to_csv("raw_photos.csv",index=False)

In [8]:
likes_df = pd.DataFrame({
    "user_id": np.random.randint(1, n_users + 1, 300000),
    "photo_id": np.random.randint(1, n_photos + 1, 300000),
    "like_time": [faker.date_time_this_year()
                  for _ in range(300000)]
})
likes_df.head()

   user_id  photo_id           like_time
0     3747     19371 2026-03-29 13:52:36
1     4413     17833 2026-03-26 01:45:03
2     6153     40019 2026-04-16 22:07:09
3     8976      4813 2026-03-09 00:27:57
4      880     46474 2026-05-28 03:08:59

In [9]:
likes_df.to_csv("raw_likes.csv",index=False)

In [10]:
comments_df = pd.DataFrame({
    "comment_id": range(1,100001),
    "user_id": np.random.randint(1, n_users + 1, 100000),
    "photo_id": np.random.randint(1, n_photos + 1, 100000),
    "comment_time": [faker.date_time_this_year()
                  for _ in range(100000)]
})
comments_df.head()

   comment_id  user_id  photo_id        comment_time
0           1     7640      8747 2026-04-13 07:55:57
1           2     6133     39774 2026-03-10 03:16:54
2           3     5187     39201 2026-05-29 12:27:37
3           4     2776     23264 2026-01-05 07:27:08
4           5     2427     33667 2026-05-17 06:37:46

In [11]:
comments_df.to_csv("raw_comments.csv",index=False)

In [12]:
follows_df = pd.DataFrame({
    "follower_id": np.random.randint(1, n_users + 1, 50000),
    "followee_id": np.random.randint(1, n_users + 1, 50000),
    "follow_time": [faker.date_time_this_year()
                  for _ in range(50000)]
})
comments_df.head()

   comment_id  user_id  photo_id        comment_time
0           1     7640      8747 2026-04-13 07:55:57
1           2     6133     39774 2026-03-10 03:16:54
2           3     5187     39201 2026-05-29 12:27:37
3           4     2776     23264 2026-01-05 07:27:08
4           5     2427     33667 2026-05-17 06:37:46

In [13]:
follows_df.to_csv("raw_follows.csv",index=False)

In [14]:
users_dirty = users_df.copy()
photos_dirty = photos_df.copy()
likes_dirty = likes_df.copy()
comments_dirty = comments_df.copy()
follows_dirty = follows_df.copy()

In [15]:
idx = users_dirty.sample(frac=0.02, random_state=9).index
users_dirty.loc[idx, "user_name"] = np.nan

In [16]:
idx = photos_dirty.sample(frac=0.01, random_state=9).index
photos_dirty.loc[idx, "upload_time"] = pd.NaT

In [17]:
duplicate_likes= likes_dirty.sample(n=5000, random_state=9)
likes_dirty = pd.concat([likes_dirty, duplicate_likes], ignore_index = True)

In [18]:
duplicate_comments = comments_dirty.sample(n=2000, random_state = 9)
comments_dirty = pd.concat([comments_dirty, duplicate_comments], ignore_index = True)

In [19]:
idx = photos_dirty.sample(n=500, random_state = 9).index
photos_dirty.loc[idx, "upload_time"] ="2036-01-01"

In [20]:
idx = follows_dirty.sample(n=1000, random_state = 9).index
follows_dirty.loc[idx, "followee_id"] = follows_dirty.loc[idx, "follower_id"]

In [21]:
bot_users = users_dirty["user_id"].sample(n=5,random_state=9)
current_max = photos_dirty["photo_id"].max()
extra_photos=[]
for bot in bot_users:
    n_posts = random.randint(500,2000)
    for i in range(n_posts):
        current_max += 1
        extra_photos.append({
            "photo_id": current_max,
            "user_id": bot,
            "upload_time":faker.date_time_this_year()
        })
extra_photos_df = pd.DataFrame(extra_photos)
photos_dirty = pd.concat([photos_dirty, extra_photos_df],ignore_index =True)

In [22]:
users_dirty.to_csv("users_dirty.csv",index=False)
photos_dirty.to_csv("photos_dirty.csv",index=False)
likes_dirty.to_csv("likes_dirty.csv",index=False)
comments_dirty.to_csv("comments_dirty.csv",index=False)
follows_dirty.to_csv("follows_dirty.csv",index=False)