In [1]:
import os
print(os.getcwd())
os.listdir()

D:\softwares\anaconda3\jupyer-notebook

['.ipynb_checkpoints',
 '1_genegrate_data.ipynb',
 'comments_dirty.csv',
 'data_cleaning.ipynb',
 'follows_dirty.csv',
 'likes_dirty.csv',
 'photos_dirty.csv',
 'raw_comments.csv',
 'raw_follows.csv',
 'raw_likes.csv',
 'raw_photos.csv',
 'raw_users.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'users_dirty.csv']

In [2]:
import pandas as pd
users_dirty = pd.read_csv("users_dirty.csv")
photos_dirty = pd.read_csv("photos_dirty.csv")
likes_dirty = pd.read_csv("likes_dirty.csv")
follows_dirty = pd.read_csv("follows_dirty.csv")
comments_dirty = pd.read_csv("comments_dirty.csv")

In [3]:
users_dirty["register_date"] = pd.to_datetime(users_dirty["register_date"])
users_dirty.info()
users_dirty.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        10000 non-null  int64
 1   user_name      9800 non-null   object
 2   register_date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 234.5+ KB

            user_id user_name               register_date
count   10000.00000      9800                       10000
unique          NaN      9270                         NaN
top             NaN  njohnson                         NaN
freq            NaN         4                         NaN
mean     5000.50000       NaN  2025-05-29 04:08:41.280000
min         1.00000       NaN         2024-05-29 00:00:00
25%      2500.75000       NaN         2024-11-29 00:00:00
50%      5000.50000       NaN         2025-06-01 00:00:00
75%      7500.25000       NaN         2025-11-24 00:00:00
max     10000.00000       NaN         2026-05-29 00:00:00
std      2886.89568       NaN                         NaN

In [4]:
users_dirty.isnull().sum()

user_id            0
user_name        200
register_date      0
dtype: int64

In [5]:
users_clean = users_dirty.copy()
users_clean["user_name"] = users_clean["user_name"].fillna("unknown_user")

In [6]:
photos_dirty["upload_time"] = pd.to_datetime(photos_dirty["upload_time"])
photos_dirty.info()
photos_dirty.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56040 entries, 0 to 56039
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   photo_id     56040 non-null  int64
 1   user_id      56040 non-null  int64
 2   upload_time  56040 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.3 MB

          photo_id       user_id                    upload_time
count  56040.00000  56040.000000                          56040
mean   28020.50000   4873.597984  2026-04-17 21:53:47.619111424
min        1.00000      1.000000            2026-01-01 00:00:40
25%    14010.75000   2402.000000  2026-02-07 22:20:10.750000128
50%    28020.50000   4763.000000     2026-03-17 17:36:28.500000
75%    42030.25000   7427.000000            2026-04-24 09:48:53
max    56040.00000  10000.000000            2036-01-01 00:00:00
std    16177.49888   2934.329313                            NaN

In [7]:
photos_clean = photos_dirty[photos_dirty["upload_time"] <= pd.Timestamp.today()]

In [8]:
likes_dirty.info()
likes_dirty.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305000 entries, 0 to 304999
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    305000 non-null  int64
 1   photo_id   305000 non-null  int64
 2   like_time  305000 non-null  object
dtypes: int64(2), object(1)
memory usage: 7.0+ MB

              user_id       photo_id            like_time
count   305000.000000  305000.000000               305000
unique            NaN            NaN               296522
top               NaN            NaN  2026-04-29 17:50:29
freq              NaN            NaN                    4
mean      5002.118180   24995.649623                  NaN
std       2883.499194   14417.383548                  NaN
min          1.000000       1.000000                  NaN
25%       2517.000000   12555.000000                  NaN
50%       4996.000000   24977.000000                  NaN
75%       7495.000000   37493.250000                  NaN
max      10000.000000   50000.000000                  NaN

In [9]:
likes_dirty.duplicated(subset=["user_id","photo_id"]).sum()

np.int64(5075)

In [10]:
likes_clean = likes_dirty.drop_duplicates(subset=["user_id","photo_id"])

In [11]:
follows_dirty.info()
follows_dirty.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   follower_id  50000 non-null  int64
 1   followee_id  50000 non-null  int64
 2   follow_time  50000 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

         follower_id  followee_id          follow_time
count   50000.000000  50000.00000                50000
unique           NaN          NaN                49915
top              NaN          NaN  2026-02-15 10:06:44
freq             NaN          NaN                    2
mean     4999.826520   5010.05120                  NaN
std      2887.623782   2889.24822                  NaN
min         1.000000      1.00000                  NaN
25%      2502.000000   2525.00000                  NaN
50%      4985.000000   5016.00000                  NaN
75%      7502.250000   7510.00000                  NaN
max     10000.000000  10000.00000                  NaN

In [12]:
follows_dirty.duplicated(subset=["follower_id","followee_id"]).sum()

np.int64(67)

In [13]:
follows_clean = follows_dirty.drop_duplicates(subset=["follower_id","followee_id"])
follows_clean.duplicated(subset=["follower_id","followee_id"]).sum()

np.int64(0)

In [14]:
comments_dirty.info()
comments_dirty.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102000 entries, 0 to 101999
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   comment_id    102000 non-null  int64
 1   user_id       102000 non-null  int64
 2   photo_id      102000 non-null  int64
 3   comment_time  102000 non-null  object
dtypes: int64(3), object(1)
memory usage: 3.1+ MB

           comment_id        user_id       photo_id         comment_time
count   102000.000000  102000.000000  102000.000000               102000
unique            NaN            NaN            NaN                99619
top               NaN            NaN            NaN  2026-03-22 11:17:34
freq              NaN            NaN            NaN                    4
mean     50022.181147    5000.791784   24960.660912                  NaN
std      28872.236327    2883.136652   14440.282296                  NaN
min          1.000000       1.000000       1.000000                  NaN
25%      25031.750000    2510.000000   12453.750000                  NaN
50%      50056.500000    5007.000000   24940.000000                  NaN
75%      75026.250000    7493.000000   37461.000000                  NaN
max     100000.000000   10000.000000   50000.000000                  NaN

In [15]:
comments_dirty.duplicated(subset=["comment_id","user_id"]).sum()

np.int64(2000)

In [16]:
comments_clean=comments_dirty.drop_duplicates(subset=["comment_id","user_id"])
comments_clean.duplicated(subset=["comment_id","user_id"]).sum()

np.int64(0)

In [17]:
photos_user = photos_clean.merge(users_clean, on = "user_id", how= "left")
photos_user.describe(include="all")

,photo_id,user_id,upload_time,user_name,register_date
count,55540.000000,55540.000000,55540,55540,55540
unique,NaN,NaN,NaN,9200,NaN
top,NaN,NaN,NaN,unknown_user,NaN
freq,NaN,NaN,NaN,7117,NaN
mean,28045.958282,4872.803871,2026-03-16 23:56:35.386658560,NaN,2025-05-22 01:02:29.081742848
min,1.000000,1.000000,2026-01-01 00:00:40,NaN,2024-05-29 00:00:00
25%,14038.750000,2402.000000,2026-02-07 12:49:05.750000128,NaN,2024-12-11 00:00:00
50%,28053.500000,4762.000000,2026-03-17 02:44:44,NaN,2025-05-21 00:00:00
75%,42062.250000,7425.000000,2026-04-23 10:00:18.249999872,NaN,2025-11-05 00:00:00
max,56040.000000,10000.000000,2026-05-30 20:12:19,NaN,2026-05-29 00:00:00
std,16183.239083,2934.352749,NaN,NaN,NaN

In [18]:
photos_user[photos_user["upload_time"]<photos_user["register_date"]]

       photo_id  user_id         upload_time         user_name register_date
3             5     7429 2026-03-06 09:40:48         brandon94    2026-04-07
4             6     8114 2026-01-24 21:15:42            cory95    2026-04-13
9            11     9378 2026-04-02 12:23:01           lvaldez    2026-05-04
20           22     1166 2026-03-07 10:39:42        velezrobin    2026-04-09
27           29     5570 2026-01-09 06:38:10  sheppardvictoria    2026-02-22
...         ...      ...                 ...               ...           ...
49465     49966     5672 2026-03-23 21:21:37          fhensley    2026-03-30
49473     49974     5112 2026-04-21 08:14:50           hnorton    2026-05-26
49483     49984     9673 2026-04-24 10:44:48        hcarpenter    2026-05-12
49487     49988     8894 2026-01-02 10:13:08      unknown_user    2026-05-21
49495     49996     1709 2026-02-18 06:57:37            vhobbs    2026-05-01

[4928 rows x 5 columns]

In [19]:
photos_user_clean = photos_user[photos_user["upload_time"] >= photos_user["register_date"]]

In [20]:
user_posts = (photos_user_clean.groupby("user_id").size().reset_index(name="post"))

In [21]:
user_posts.describe(include="all")

            user_id         post
count   9552.000000  9552.000000
mean    5002.025963     5.298576
std     2890.920114    29.481000
min        1.000000     1.000000
25%     2496.750000     3.000000
50%     5006.500000     4.000000
75%     7508.500000     6.000000
max    10000.000000  1848.000000

In [30]:
Q1 = user_posts["post"].quantile(0.25)
Q3 = user_posts["post"].quantile(0.75)
IQR = Q3 - Q1
threshold = Q1 + 1.5 * IQR

In [31]:
user_posts["is_abnormal"] = (user_posts["post"] > threshold)
user_posts[user_posts["is_abnormal"]]

      user_id  post  is_abnormal
1           2     8         True
28         33     8         True
31         36     8         True
34         39     8         True
40         46     8         True
...       ...   ...          ...
9530     9979    10         True
9534     9983     8         True
9536     9985     9         True
9537     9986     8         True
9551    10000     8         True

[1057 rows x 3 columns]

In [33]:
users_clean.to_csv("users_clean.csv", index=False)
photos_clean.to_csv("photos_clean.csv", index=False)
likes_clean.to_csv("likes_clean.csv", index=False)
follows_clean.to_csv("follows_clean.csv", index=False)
comments_clean.to_csv("comments_clean.csv", index=False)